{"datetime": "2023-02-20 01:58:21", "loglevel": "WARNING", "logger": "uvicorn.error", "message": "StatReload detected changes in 'app.py'. Reloading..."}
{"datetime": "2023-02-20 01:58:24", "loglevel": "WARNING", "logger": "uvicorn.error", "message": "StatReload detected changes in 'app.py'. Reloading..."}
{"datetime": "2023-02-20 01:58:28", "loglevel": "ERROR", "logger": "app", "message": "Traceback (most recent call last):\n  File \"/home/ilsur/x/projects/Diplom/venv/lib/python3.9/site-packages/starlette/middleware/base.py\", line 77, in call_next\n    message = await recv_stream.receive()\n  File \"/home/ilsur/x/projects/Diplom/venv/lib/python3.9/site-packages/anyio/streams/memory.py\", line 94, in receive\n    return self.receive_nowait()\n  File \"/home/ilsur/x/projects/Diplom/venv/lib/python3.9/site-packages/anyio/streams/memory.py\", line 87, in receive_nowait\n    raise EndOfStream\nanyio.EndOfStream\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"./app.py\", line 22, in db_session_middleware\n    response = await call_next(request)\n  File \"/home/ilsur/x/projects/Diplom/venv/lib/python3.9/site-packages/starlette/middleware/base.py\", line 80, in call_next\n    raise app_exc\n  File \"/home/ilsur/x/projects/Diplom/venv/lib/python3.9/site-packages/starlette/middleware/base.py\", line 69, in coro\n    await self.app(scope, receive_or_disconnect, send_no_error)\n  File \"/home/ilsur/x/projects/Diplom/venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py\", line 79, in __call__\n    raise exc\n  File \"/home/ilsur/x/projects/Diplom/venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py\", line 68, in __call__\n    await self.app(scope, receive, sender)\n  File \"/home/ilsur/x/projects/Diplom/venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py\", line 21, in __call__\n    raise e\n  File \"/home/ilsur/x/projects/Diplom/venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py\", line 18, in __call__\n    await self.app(scope, receive, send)\n  File \"/home/ilsur/x/projects/Diplom/venv/lib/python3.9/site-packages/starlette/routing.py\", line 706, in __call__\n    await route.handle(scope, receive, send)\n  File \"/home/ilsur/x/projects/Diplom/venv/lib/python3.9/site-packages/starlette/routing.py\", line 276, in handle\n    await self.app(scope, receive, send)\n  File \"/home/ilsur/x/projects/Diplom/venv/lib/python3.9/site-packages/starlette/routing.py\", line 66, in app\n    response = await func(request)\n  File \"/home/ilsur/x/projects/Diplom/venv/lib/python3.9/site-packages/fastapi/routing.py\", line 237, in app\n    raw_response = await run_endpoint_function(\n  File \"/home/ilsur/x/projects/Diplom/venv/lib/python3.9/site-packages/fastapi/routing.py\", line 163, in run_endpoint_function\n    return await dependant.call(**values)\n  File \"./routes.py\", line 31, in get_ticket_priority_all\n    raise Exception(\"TEST\")\nException: TEST\n"}
{"datetime": "2023-02-20 01:58:43", "loglevel": "WARNING", "logger": "uvicorn.error", "message": "StatReload detected changes in 'utils.py'. Reloading..."}
{"datetime": "2023-02-20 01:58:49", "loglevel": "WARNING", "logger": "uvicorn.error", "message": "StatReload detected changes in 'routes.py'. Reloading..."}
{"datetime": "2023-02-20 01:58:59", "loglevel": "WARNING", "logger": "uvicorn.error", "message": "StatReload detected changes in 'routes.py'. Reloading..."}
{"datetime": "2023-02-20 01:59:29", "loglevel": "WARNING", "logger": "uvicorn.error", "message": "StatReload detected changes in 'app.py'. Reloading..."}
{"datetime": "2023-02-20 01:59:32", "loglevel": "WARNING", "logger": "uvicorn.error", "message": "StatReload detected changes in 'app.py'. Reloading..."}
